
spring:
  application:
    name: item-service
    
  cloud:
    config:
      override-none: true
      
  rabbitmq:
    host: 39.105.171.30
    port: 5672
    username: maccy
    password: 123456
    
server:
  port: 8001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

      